/**
 * Galéria realizácií: všetky použiteľné fotografie klienta z `public/assets`.
 *
 * Vynechané sú len logo (90, 91) a `10-titulka_o_firme.jpg` (firemná titulka,
 * nie realizácia). Rozmery `w` a `h` sú namerané cez
 * `sips -g pixelWidth -g pixelHeight public/assets/<súbor>`, nie odhadnuté.
 *
 * Miesta pochádzajú z názvov súborov a z už odsúhlasených sekcií
 * predchádzajúceho behu. Kde plný názov miesta nie je istý (skratky MT, TN,
 * BB, PD, TT, súbory `Subor_00*` a číselné názvy z Facebooku), stojí
 * `isteMiesto: false` a pravdivé „Realizácia klienta“; odhady sú v
 * `poznamky/MAPA-OBSAHU.md` v zozname pre handover. Roky nemáme, neuvádzame ich.
 *
 * `sluzba` je slug služby, ku ktorej fotka patrí (krížové odkazy medzi
 * galériou a stránkami služieb). Priradenie vychádza zo stránky pôvodného
 * webu, na ktorej fotka bola (`pipeline/structure.json`, pole `sourcePage`),
 * a z toho, čo je na fotke naozaj vidieť.
 *
 * `duplikatOf` označuje malý orez tej istej scény, ktorý pôvodný web používal
 * ako dlaždicu služby. Do galérie ide `GALERIA` (bez duplikátov), `REALIZACIE`
 * ostáva úplným inventárom fotiek.
 */
export const REALIZACIE = [
  {
    id: 'zubacka-nastupiste-dlazdica',
    src: '00-ZubaC48Dka-600x390.jpg',
    w: 600,
    h: 390,
    alt: 'Vodiaca línia a varovné pásy na nástupišti, Zubačka',
    miesto: 'Zubačka',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
    duplikatOf: '12-ZubaC48Dka-scaled.jpg',
  },
  {
    id: 'medeny-hamor-obrubnik-dlazdica',
    src: '01-Medeny_Hamor_1-600x390.jpg',
    w: 600,
    h: 390,
    alt: 'Lepený cestný obrubník na novom asfaltovom kryte, Medený Hámor',
    miesto: 'Medený Hámor',
    isteMiesto: true,
    prvok: 'Lepený obrubník',
    prostredie: 'Exteriér',
    sluzba: 'lepene-obrubniky',
    duplikatOf: '13-Medeny_Hamor_1-scaled.jpg',
  },
  {
    id: 'vodorovne-znacenie-dlazdica',
    src: '02-PD-1-600x390.jpg',
    w: 600,
    h: 390,
    alt: 'Vodorovné dopravné značenie jazdných pruhov a parkovacích boxov',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Vodorovné dopravné značenie',
    prostredie: 'Exteriér',
    sluzba: 'vodorovne-dopravne-znacenie',
    duplikatOf: '14-PD-1.jpg',
  },
  {
    id: 'retardery-dvojrad',
    src: '03-MT_1-600x390.jpg',
    w: 600,
    h: 390,
    alt: 'Spomaľovače dopravy Kölner Teller osadené v dvojrade na vozovke',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Spomaľovače dopravy',
    prostredie: 'Exteriér',
    sluzba: 'spomalovace-dopravy',
  },
  {
    id: 'zalievka-skary',
    src: '04-zalievkove_hmoty_01-600x390.jpg',
    w: 600,
    h: 390,
    alt: 'Aplikácia zálievkovej hmoty do škáry v kryte vozovky',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Zálievková hmota',
    prostredie: 'Exteriér',
    sluzba: 'zalievkove-a-vyspravkove-hmoty',
  },
  {
    id: 'filakovo-protismykove-pasy',
    src: '05-Protismykove-pasy-Filakovo3-416x390.jpg',
    w: 416,
    h: 390,
    alt: 'Protišmykové pásy na schodiskovom stupni, Fiľakovo',
    miesto: 'Fiľakovo',
    isteMiesto: true,
    prvok: 'Protišmykový náter',
    prostredie: 'Exteriér',
    sluzba: 'protismykovy-nater',
  },
  {
    id: 'cyklotrasa-piktogram',
    src: '06-IMG_1565-480x390.jpg',
    w: 480,
    h: 390,
    alt: 'Cyklotrasa s farebným povrchom a piktogramom bicykla',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Cyklotrasa',
    prostredie: 'Exteriér',
    sluzba: 'cyklotrasy',
  },
  {
    id: 'stitky-braille',
    src: '07-Braill-600x390.jpg',
    w: 600,
    h: 390,
    alt: 'Orientačné štítky s Braillovým písmom a piktogramami',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Štítky s Braillovým písmom',
    prostredie: 'Interiér',
    sluzba: 'stitky-braillovo-pismo',
  },
  {
    id: 'bosakova-odstranene-znacenie',
    src: '08-BA_Bosakova-600x390.jpg',
    w: 600,
    h: 390,
    alt: 'Priechod pre chodcov po odstránení starého vodorovného značenia, Bratislava Bosákova',
    miesto: 'Bratislava Bosákova',
    isteMiesto: true,
    prvok: 'Odstránené značenie',
    prostredie: 'Exteriér',
    sluzba: 'odstranenie-znacenia',
  },
  {
    id: 'zubacka-nastupiste',
    src: '12-ZubaC48Dka-scaled.jpg',
    w: 1400,
    h: 1050,
    alt: 'Vodiaca línia a varovné pásy na nástupišti, Zubačka',
    miesto: 'Zubačka',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'medeny-hamor-obrubnik',
    src: '13-Medeny_Hamor_1-scaled.jpg',
    w: 960,
    h: 1280,
    alt: 'Lepený cestný obrubník pozdĺž novej vozovky, Medený Hámor',
    miesto: 'Medený Hámor',
    isteMiesto: true,
    prvok: 'Lepený obrubník',
    prostredie: 'Exteriér',
    sluzba: 'lepene-obrubniky',
  },
  {
    id: 'vodorovne-znacenie-komunikacia',
    src: '14-PD-1.jpg',
    w: 721,
    h: 1600,
    alt: 'Obnovené vodorovné dopravné značenie na miestnej komunikácii',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Vodorovné dopravné značenie',
    prostredie: 'Exteriér',
    sluzba: 'vodorovne-dopravne-znacenie',
  },
  {
    id: 'protismykovy-nater-nastupiste',
    src: '19-Znacenie-pre-nevidiacich-varovny-pas-a-protismykovy-nater-sc.jpg',
    w: 1600,
    h: 1200,
    alt: 'Protišmykový náter hrany nástupišťa a modrý signálny pás',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Protišmykový náter',
    prostredie: 'Exteriér',
    sluzba: 'protismykovy-nater',
  },
  {
    id: 'varovny-pas-chodnik',
    src: '20-BB-1-scaled.jpg',
    w: 1200,
    h: 1600,
    alt: 'Červený varovný pás na chodníku pred priechodom pre chodcov',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Varovný pás',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'signalny-pas-priechod-ba',
    src: '21-BA.jpg',
    w: 960,
    h: 720,
    alt: 'Červený signálny pás vedúci k priechodu pre chodcov, Bratislava',
    miesto: 'Bratislava',
    isteMiesto: true,
    prvok: 'Signálny pás',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'signalny-pas-vstup',
    src: '22-Znacenie-pre-nevidiacich-varovny-pas-a-protismykovy-nater-sc.jpg',
    w: 1600,
    h: 1200,
    alt: 'Modrý signálny pás a varovný pás pri vstupe do budovy',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Signálny pás',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'varovny-pas-ba',
    src: '23-BA-1-scaled.jpg',
    w: 1600,
    h: 1200,
    alt: 'Varovný pás z tmavého štruktúrovaného značenia na dlažbe, Bratislava',
    miesto: 'Bratislava',
    isteMiesto: true,
    prvok: 'Varovný pás',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'vodiaca-linia-pozdlz-cesty',
    src: '24-44495307_320444702084823_8875250875791048704_n-2048x1536.jpg',
    w: 1600,
    h: 1200,
    alt: 'Svetlá vodiaca línia s varovným pásom pozdĺž novej vozovky',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Vodiaca línia',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nivy-vodiaca-linia',
    src: '25-BA_nivy_hbreavis-scaled.jpg',
    w: 1200,
    h: 1600,
    alt: 'Vodiaca línia a varovný pás medzi obrubníkmi, Bratislava Nivy',
    miesto: 'Bratislava Nivy',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'vodiaca-linia-stupanie',
    src: '26-TN_1-scaled.jpg',
    w: 1050,
    h: 1400,
    alt: 'Červená vodiaca línia vedená po okraji stúpajúcej komunikácie',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Vodiaca línia',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'tornala-signalny-pas',
    src: '27-Tornala.jpg',
    w: 1400,
    h: 1050,
    alt: 'Červený signálny pás a vodiaca línia na dlažbe, Tornaľa',
    miesto: 'Tornaľa',
    isteMiesto: true,
    prvok: 'Signálny pás',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nivy-interier-hala',
    src: '28-BA_nivy_1-scaled.jpg',
    w: 1200,
    h: 1600,
    alt: 'Vodiaca línia v hale terminálu, Bratislava Nivy',
    miesto: 'Bratislava Nivy',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Interiér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'vodiaca-linia-ba-zlta',
    src: '29-Vodiaca-linia-BA.jpg',
    w: 466,
    h: 350,
    alt: 'Žltá vodiaca línia na betónovom povrchu, Bratislava',
    miesto: 'Bratislava',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'priechod-signalny-pas',
    src: '30-IMAG0678.jpg',
    w: 1200,
    h: 902,
    alt: 'Signálny pás a vodiaca línia v priechode pre chodcov',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Vodiaca línia v priechode pre chodcov',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'priechod-vodiaca-linia-ba',
    src: '31-Vodiaca-linia-v-priechode-BA.jpg',
    w: 444,
    h: 333,
    alt: 'Vodiaca línia v priechode pre chodcov, Bratislava',
    miesto: 'Bratislava',
    isteMiesto: true,
    prvok: 'Vodiaca línia v priechode pre chodcov',
    prostredie: 'Exteriér',
    sluzba: 'vodorovne-dopravne-znacenie',
  },
  {
    id: 'priechod-nerezova-linia',
    src: '32-33367602_1897316533626452_7756924709983223808_n.jpg',
    w: 1200,
    h: 900,
    alt: 'Vodiaca línia z nerezových indikátorov v priechode pre chodcov',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Vodiaca línia v priechode pre chodcov',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nerezove-indikatory-varovny-pas',
    src: '33-Subor_008-e1517561069972.jpg',
    w: 1200,
    h: 900,
    alt: 'Varovný pás z nerezových indikátorov osadených v betóne',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Nerezové indikátory',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nerezove-indikatory-chodnik',
    src: '34-Subor_009-e1511969915236.jpg',
    w: 1200,
    h: 900,
    alt: 'Pás nerezových indikátorov medzi asfaltom a dlažbou chodníka',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Nerezové indikátory',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nerezove-indikatory-detail',
    src: '35-Subor_0031.jpg',
    w: 1200,
    h: 900,
    alt: 'Detail osadenia nerezových indikátorov do betónového povrchu',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Nerezové indikátory',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nivy-interier-vstup',
    src: '36-BA_nivy_3-1-scaled.jpg',
    w: 1600,
    h: 1200,
    alt: 'Vodiaca línia z nerezových indikátorov pri vstupe do haly, Bratislava Nivy',
    miesto: 'Bratislava Nivy',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Interiér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nivy-interier-krizenie',
    src: '37-BA_nivy_2-1-scaled.jpg',
    w: 1600,
    h: 1200,
    alt: 'Kríženie vodiacich línií na tmavej dlažbe v interiéri, Bratislava Nivy',
    miesto: 'Bratislava Nivy',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Interiér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'mosadzne-indikatory-varovny-pas',
    src: '38-50466328_389870655112519_8920376035585818624_n.jpg',
    w: 1200,
    h: 900,
    alt: 'Varovný pás z mosadzných indikátorov osadených v betóne',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Mosadzné indikátory',
    prostredie: 'Exteriér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nivy-interier-chodba',
    src: '39-BA_nivy-1-scaled.jpg',
    w: 1200,
    h: 1600,
    alt: 'Vodiaca línia z nerezových indikátorov v chodbe, Bratislava Nivy',
    miesto: 'Bratislava Nivy',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Interiér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'nivy-interier-linia',
    src: '40-BA_nivy_1-1-scaled.jpg',
    w: 1200,
    h: 1600,
    alt: 'Vodiaca línia vedená halou terminálu, Bratislava Nivy',
    miesto: 'Bratislava Nivy',
    isteMiesto: true,
    prvok: 'Vodiaca línia',
    prostredie: 'Interiér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
  {
    id: 'mosadzne-indikatory-interier',
    src: '41-49947869_2371119383145462_2185064813703462912_n.jpg',
    w: 1200,
    h: 900,
    alt: 'Varovný pás z mosadzných indikátorov v dlažbe interiéru',
    miesto: 'Realizácia klienta',
    isteMiesto: false,
    prvok: 'Mosadzné indikátory',
    prostredie: 'Interiér',
    sluzba: 'znacenie-pre-nevidiacich',
  },
]

/** Galéria bez malých orezov, ktoré duplikujú väčšiu fotku tej istej scény. */
export const GALERIA = REALIZACIE.filter((r) => !r.duplikatOf)

/** Typy prvkov pre filter, v poradí prvého výskytu v galérii. */
export const TYPY_PRVKOV = [...new Set(GALERIA.map((r) => r.prvok))]

/** Miesta pre filter; „Realizácia klienta“ je pravdivá náhrada za neisté miesto. */
export const MIESTA = [...new Set(GALERIA.map((r) => r.miesto))]

/** Exteriér a interiér, ako obsah delí aj pôvodný web. */
export const PROSTREDIA = [...new Set(GALERIA.map((r) => r.prostredie))]

/** Realizácie jednej služby (krížový odkaz zo stránky služby do galérie). */
export const realizaciePodlaSluzby = (slug) => GALERIA.filter((r) => r.sluzba === slug)
